### ISSUE TITLE
LVS known issues

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/caravel-gf180mcu#165]
1. adding `fill10` in `chip_io` gl netlist generates instance mismatches. The only way I could get rid of it was removing `fill10` completely
2. `chip_io` has property errors that originated from pad property errors
3. filtering `fill`, `filltie` and `endcap` because calibre doesn't extract them correctly.

**Comment by RTimothyEdwards** [comment]
I am able to get a correct exact LVS match at the transistor level for `chip_io` using magic and netgen.

**Comment by jeffdi** [comment]
Review and close if appropriate.

**Comment by marwaneltoukhy** [comment]
That was related to calibre.
