### ISSUE TITLE
simple_por power pins

### ISSUE THREAD

**Issue by mo-hosni** [efabless/caravel-gf180mcu#31]
simple_por power has a mismatch in power pins between the RTL and the LEF/GDS views and the power pins are not easily accessible.

Suggestions:
- Power pins be VDD and VSS in all views.
- Power rings to be added.

**Comment by RTimothyEdwards** [comment]
@mo-hosni :  I need to know what size/pitch/layers to make the power rings.

**Comment by mo-hosni** [comment]
@RTimothyEdwards: Well, I locally changed the pin names in the LEF view from `vdd` and `vss` to `VDD` and `VSS` to match the RTL, and I was able to connect the por to the PDN using a custom script. So, I think we can close this issue and then review the power connections once I make a pull request with the full caravel.
