### ISSUE TITLE
Mismatched views

### ISSUE THREAD

**Issue by mo-hosni** [efabless/caravel-gf180mcu#39]
The following blocks have mismatched views in the repo
- gpio_defaults_block_007: Has no GDS view. DEF and LEF do not match the MAG view.
- gpio_defaults_block_009: Has no GDS view. DEF and LEF do not match the MAG view.
- gpio_defaults_block_087: Has no GDS view. DEF and LEF do not match the MAG view.
- user_id_programming: GDS, DEF, and LEF do not match the MAG view.
- chip_io: GDS, DEF, and LEF do not match the MAG view.

DEF is not really an issue for me, GDS and LEF views are needed for PnR.

**Comment by RTimothyEdwards** [comment]
Fixed by PR #44
