### ISSUE TITLE
caravel_core is not LVS clean.

### ISSUE THREAD

**Issue by mo-hosni** [efabless/caravel-gf180mcu#56]
There are net mismatches in the nets on the SRAM interface in the abstract LVS. 
I reviewed some of them and the layout was correct.
This might be a problem with the extraction from LEF, not the layout. 

A device-level LVS is needed.

**Comment by marwaneltoukhy** [comment]
related to https://github.com/RTimothyEdwards/netgen/issues/68

**Comment by marwaneltoukhy** [comment]
caravel_core is now clean if we abstract SRAM cells, user_project_wrapper and simple_por.
Issue for SRAM: https://github.com/efabless/caravel-gf180mcu/issues/87
Issue for simple_por: https://github.com/efabless/caravel-gf180mcu/issues/79
