### ISSUE TITLE
caravel.v instantiates chip_io with signals connected directly to power pins

### ISSUE THREAD

**Issue by RTimothyEdwards** [efabless/caravel-gf180mcu#59]
```
    chip_io padframe(
        // Package Pins
`ifdef USE_POWER_PINS
        .VDD    (VDD),          // Common padframe/ESD supply
        .VSS    (VSS),          // Common digital ground
        .gpio_pu_select_core(VSS),
        .gpio_pd_select_core(VSS),
        .gpio_schmitt_select_core(VSS),
        .gpio_slew_select_core(VSS),
`endif
```

(1) Signal pins should _never_ be put inside a USE_POWER_PINS block
(2) Signals should never be connected directly to power supplies

This needs either a constant-value output from the SoC, or (preferably) add four bits to the GPIO control register in the SoC core to drive these four signals.

**Comment by mo-hosni** [comment]
@RTimothyEdwards 
I fixed that in the PnR branch that I am working on and added the connection to the layout.
Check this commit. https://github.com/efabless/caravel-gf180mcu/commit/6ab794ee3a678e2bd5fedf95d57673be5f4571bd
