### ISSUE TITLE
Some std cells in the RTL get resized in timing optmizations.

### ISSUE THREAD

**Issue by mo-hosni** [efabless/caravel-gf180mcu#60]
You need to review every standard cell instantiated in the RTL and check whether or not it gets resized and whether or not resizing is acceptable.

**Comment by jeffdi** [comment]
addressed through no-touch attribute currently.

**Comment by jeffdi** [comment]
@RTimothyEdwards can you please review and comment?

**Comment by jeffdi** [comment]
Tim confirmed.  The only block is affected is the DLL.  The DLL is experimental and will be removed from the testbench list for this release.
