### ISSUE TITLE
user_id_programming gl netlist is missing 

### ISSUE THREAD

**Issue by M0stafaRady** [efabless/caravel-gf180mcu#61]
`user_id_programming` gate-level netlist is missing.

**Comment by RTimothyEdwards** [comment]
Please don't assign these to me.  I don't generate gate-level netlists of hand-built designs.  I provide GDS and DEF, and somebody on your end has been using those to generate gate-level netlists.

**Comment by RTimothyEdwards** [comment]
@shalan :  But it appears that all other gate-level netlists of blocks that were not synthesized were somehow generated by passing them through yosys.  I didn't create those gate-level netlists.

**Comment by RTimothyEdwards** [comment]
This is fixed by PR #68
