### ISSUE TITLE
SRAM 512 not DRC clean

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/caravel-gf180mcu#70]
## Expected Behavior
`sram512x8m8wm1` DRC clean

## Actual Behavior
`sram512x8m8wm1` has a violation in rule `NW.2b_5V_`

## Steps to Reproduce the Problem

1. build the pdk
2. run `python3 run_drc.py --gf180mcu=C --path=$PDK_ROOT/$PDK/libs.ref/gf180mcu_fd_ip_sram/gds/gf180mcu_fd_ip_sram__sram512x8m8wm1.gds`

## Specifications

- Klayout Version: 0.28
- Platform: Debian

Original issue filed here https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/issues/7

**Comment by RTimothyEdwards** [comment]
As noted in the conference call, this issue is with the klayout DRC deck implementation, as the nwells in question are at the same potential.  The "different potential" nwell spacing rule does not apply, and so there is no real DRC error here.

**Comment by marwaneltoukhy** [comment]
SRAM DRC is clean when enabling connectivity.
